# Lint

# For debug
disabled_rules:
  - statement_position
  - unused_setter_value
  - notification_center_detachment
  - large_tuple
  - cyclomatic_complexity
  - multiple_closures_with_trailing_closure
  - trailing_whitespace
  - todo
  - force_try
  - force_cast
# # For release 
# disabled_rules:

# force_cast: warning # implicitly
# force_try:
#   severity: warning # explicitly


opt_in_rules:
  - file_header

included:
  - LazyPhish

excluded: 
  - Carthage
  - Pods
  - build

line_length: 110

function_body_length:
  warning: 120
  error: 400

type_body_length:
  warning: 500
  error: 1200

file_length:
  warning: 900
  error: 1600

type_name:
  min_length: 3
  max_length:
    warning: 40
    error: 50

identifier_name:
  min_length: 3
  excluded: # excluded via string array
    - id
    - URL
    - url
    - x
    - y
    - i
    - j
    - n
    - vm
reporter: "xcode" # reporter type (xcode, json, csv, checkstyle, junit, html, emoji)
